version: "3.7"

services:

  asterisk:
    build: ./
    volumes:
      - "./etc/asterisk/:/etc/asterisk/"
    cap_add:
     - SYS_NICE

  db:
    image: "mysql:5"
    environment:
      - MYSQL_ROOT_PASSWORD=example